(function() {

    module('Sync integration test');


    asyncTest('patch - simulate a sync update/patch', function () {
        var documentId = uuid();
        var clientId = "testClientId";
        var addDocument = { msgType: 'add', docId: documentId, content: 'Do or do not, there is no try.' };
        var addShadow = { msgType: 'shadow', docId: documentId, clientId: clientId } ;
        // the clients diffs would be generated by the client side JS library.
        var clientEdits = { msgType: 'edits', 
            docId: documentId, 
            clientId: clientId, 
            version: 0, 
            checksum: '', 
            diffs: [{operation: 'UNCHANGED', text: 'Do or do not, there is no try'},{operation: 'DELETE', text: '.'},{operation: 'ADD', text: '!'}]}
        var url = 'ws://localhost:7777/sync';
        var ws = new WebSocket(url);

        ws.onopen = function( evt ) {
            ws.send( JSON.stringify ( addDocument ) );
            ws.send( JSON.stringify ( addShadow ) );
            ws.send( JSON.stringify ( clientEdits ) );
        };

        var counter = 0;
        ws.onmessage = function ( evt ) {
            var json = JSON.parse( evt.data );
            switch ( counter ) {
                case 0: 
                    equal( json.result, 'ADDED', 'Document should have been added' );
                    break;
                case 1: 
                    equal( json.result, 'ADDED', 'Shadow Document should have been added' );
                    break;
                case 2: 
                    equal( json.result, 'PATCHED', 'The patch should have been applied' );
                    break;
                case 3:
                    equal( json.msgType, 'edits', 'The server should have generated an edit' );
                    equal( json.clientId, clientId, 'The clientId should match. This is who made the update.' );
                    equal( json.version, 1, 'Version of the server document recieved.' );
                    equal( json.diffs[0].operation, 'UNCHANGED', 'Since we made the change now change is required.' );
                    equal( json.diffs[0].text, 'Do or do not, there is no try!', 'The text should be updated.' );
                    start();
                    break;
            }
            counter++;
        };

        ws.onerror = function ( e ) {
            ok( false, 'Failed to connect to WebSocket server [' + url + ']' );
            start();
        };
    });

    function uuid()
    {
        return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function( c ) {
            var r = Math.random()*16|0, v = c === 'x' ? r : (r&0x3|0x8);
            return v.toString( 16 );
        });
    }

})();
